name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --name Kopirka --add-data "assets;assets" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: Kopirka-Windows
        path: dist/Kopirka/
